import React, { useState } from 'react';
import { BlindSpotAnalysis } from '../types';
import {
  Eye,
  ShieldAlert,
  Layers,
  HelpCircle,
  Scale,
  CheckSquare,
  Square,
  CheckCircle,
  Info,
  GitBranch,
  TrendingUp,
  Download,
  Share2,
  Clock,
  Zap,
} from 'lucide-react';

interface BlindSpotResultsProps {
  analysis: BlindSpotAnalysis;
}

export const BlindSpotResults: React.FC<BlindSpotResultsProps> = ({ analysis }) => {
  const [addressedAssumptions, setAddressedAssumptions] = useState<Record<string, boolean>>({});
  const [completedQuestions, setCompletedQuestions] = useState<Record<number, boolean>>({});

  const toggleAssumption = (id: string) => {
    setAddressedAssumptions((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const toggleQuestion = (idx: number) => {
    setCompletedQuestions((prev) => ({ ...prev, [idx]: !prev[idx] }));
  };

  const totalItems = analysis.hiddenAssumptions.length + analysis.probingQuestions.length;
  const itemsCompleted =
    Object.values(addressedAssumptions).filter(Boolean).length +
    Object.values(completedQuestions).filter(Boolean).length;
  const clarityScore = Math.round((itemsCompleted / (totalItems || 1)) * 100);

  const handleExportBrief = () => {
    const briefText = `# 👁️ Critical Decision Brief: ${analysis.decisionTitle}
Generated by BLINDSPOT AI Engine on ${new Date(analysis.timestamp).toLocaleDateString()}

## 📝 Summary
${analysis.summary}

## 🔍 Unstated Assumptions
${analysis.hiddenAssumptions
  .map((a) => `- [${addressedAssumptions[a.id] ? 'x' : ' '}] **${a.title}** (${a.riskLevel} Risk): ${a.description}`)
  .join('\n')}

## 👁️ Overlooked Secondary Factors
${analysis.overlookedFactors.map((f) => `- **[${f.category}] ${f.factor}:** ${f.impact}`).join('\n')}

## 🧠 Cognitive Biases Detected
${analysis.cognitiveBiases.map((b) => `- **${b.biasName}:** ${b.explanation}`).join('\n')}

## ❓ Probing Questions for Reflection
${analysis.probingQuestions.map((q, i) => `- [${completedQuestions[i] ? 'x' : ' '}] ${q}`).join('\n')}

## 🔮 Scenario Simulations
${analysis.scenarios ? analysis.scenarios.map((s) => `### ${s.scenarioName}\n${s.description}\n*Key Uncertainties:* ${s.keyUncertainties.join(', ')}`).join('\n\n') : ''}

## 🔀 Alternative Paths
${analysis.alternativePaths ? analysis.alternativePaths.map((a) => `### ${a.optionTitle}\n${a.description}\n*Trade-off vs Primary Choice:* ${a.tradeoffComparison}`).join('\n\n') : ''}

---
*Note: This analysis is non-directive and designed to help you examine your assumptions before deciding.*
`;

    const blob = new Blob([briefText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Blindspot_Decision_Brief_${analysis.decisionTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 my-6 animate-fadeIn" aria-live="polite">
      <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2 text-amber-400 mb-1">
            <Eye className="w-5 h-5" />
            <h2 className="text-xl font-bold text-white">{analysis.decisionTitle}</h2>
          </div>
          <div className="flex items-center space-x-3 text-xs text-slate-400">
            <span className="flex items-center space-x-1">
              <Clock className="w-3.5 h-3.5" />
              <span>{new Date(analysis.timestamp).toLocaleTimeString()}</span>
            </span>
            {analysis.latencyMs && (
              <span className="flex items-center space-x-1 text-emerald-400">
                <Zap className="w-3.5 h-3.5" />
                <span>Gemini Telemetry: {analysis.latencyMs}ms</span>
              </span>
            )}
          </div>
        </div>

        <div className="flex items-center space-x-3 w-full md:w-auto justify-end">
          <button
            onClick={handleExportBrief}
            className="inline-flex items-center space-x-2 bg-slate-800 hover:bg-slate-700 text-slate-200 px-4 py-2 rounded-xl text-xs font-semibold border border-slate-700 transition shadow-md"
          >
            <Download className="w-4 h-4 text-amber-400" />
            <span>Export Brief (.md)</span>
          </button>
        </div>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4">
          <div>
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-emerald-400" />
              Reasoning Clarity & Evaluation Score
            </h3>
            <p className="text-xs text-slate-400">
              Check off assumptions and reflection questions as you examine them to increase your decision clarity score.
            </p>
          </div>
          <div className="text-right">
            <span className="text-2xl font-black text-amber-400">{clarityScore}%</span>
            <p className="text-[10px] text-slate-400 font-medium">Clarity Score</p>
          </div>
        </div>

        <div className="w-full bg-slate-950 rounded-full h-3 p-0.5 border border-slate-800 overflow-hidden">
          <div
            className="bg-gradient-to-r from-amber-500 via-purple-500 to-emerald-400 h-full rounded-full transition-all duration-500 shadow-lg"
            style={{ width: `${clarityScore}%` }}
          />
        </div>
      </div>

      <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 shadow-xl">
        <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Context & Decision Tension</h3>
        <p className="text-sm text-slate-300 leading-relaxed bg-slate-950 p-4 rounded-2xl border border-slate-800/80">
          {analysis.summary}
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-4">
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <div className="flex items-center space-x-2">
              <ShieldAlert className="w-5 h-5 text-rose-400" />
              <h3 className="text-base font-bold text-white">1. Unstated Assumptions</h3>
            </div>
            <span className="text-[11px] text-slate-400">Click to mark as examined</span>
          </div>

          <div className="space-y-3">
            {analysis.hiddenAssumptions.map((item) => {
              const isChecked = !!addressedAssumptions[item.id];
              return (
                <button
                  key={item.id}
                  onClick={() => toggleAssumption(item.id)}
                  className={`w-full text-left p-4 rounded-2xl border transition ${
                    isChecked
                      ? 'bg-emerald-950/20 border-emerald-500/40 text-emerald-200'
                      : 'bg-slate-950 border-slate-800 hover:border-slate-700 text-slate-200'
                  }`}
                >
                  <div className="flex items-center justify-between mb-1.5">
                    <div className="flex items-center space-x-2">
                      {isChecked ? (
                        <CheckCircle className="w-4 h-4 text-emerald-400 shrink-0" />
                      ) : (
                        <Square className="w-4 h-4 text-slate-500 shrink-0" />
                      )}
                      <h4 className="text-sm font-semibold">{item.title}</h4>
                    </div>
                    <span
                      className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wider ${
                        item.riskLevel === 'High'
                          ? 'bg-rose-500/20 text-rose-400 border border-rose-500/30'
                          : item.riskLevel === 'Medium'
                          ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30'
                          : 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                      }`}
                    >
                      {item.riskLevel} Risk
                    </span>
                  </div>
                  <p className="text-xs text-slate-400 pl-6 leading-relaxed">{item.description}</p>
                </button>
              );
            })}
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-4">
          <div className="flex items-center space-x-2 border-b border-slate-800 pb-3">
            <Layers className="w-5 h-5 text-indigo-400" />
            <h3 className="text-base font-bold text-white">2. Overlooked Secondary Factors</h3>
          </div>
          <div className="space-y-3">
            {analysis.overlookedFactors.map((item, idx) => (
              <div key={idx} className="bg-slate-950 border border-slate-800/80 rounded-2xl p-4 hover:border-slate-700 transition">
                <div className="flex items-center space-x-2 mb-1">
                  <span className="text-[10px] font-bold uppercase tracking-wider bg-indigo-500/15 text-indigo-300 px-2 py-0.5 rounded-md border border-indigo-500/20">
                    {item.category}
                  </span>
                  <h4 className="text-xs font-semibold text-slate-200">{item.factor}</h4>
                </div>
                <p className="text-xs text-slate-400 leading-relaxed">{item.impact}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {analysis.scenarios && analysis.scenarios.length > 0 && (
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl">
          <div className="flex items-center space-x-2 border-b border-slate-800 pb-3 mb-4">
            <GitBranch className="w-5 h-5 text-purple-400" />
            <h3 className="text-base font-bold text-white">3. Scenario Stress-Tester (Simulated Futures)</h3>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {analysis.scenarios.map((sc, idx) => (
              <div key={idx} className="bg-slate-950 border border-slate-800 p-4 rounded-2xl">
                <span className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full border inline-block mb-2 ${
                  sc.scenarioName === 'Best Case' ? 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30' :
                  sc.scenarioName === 'Worst Case' ? 'bg-rose-500/15 text-rose-400 border-rose-500/30' :
                  'bg-blue-500/15 text-blue-400 border-blue-500/30'
                }`}>
                  {sc.scenarioName}
                </span>
                <p className="text-xs text-slate-300 mb-3 leading-relaxed">{sc.description}</p>
                <div className="text-[11px] text-slate-400 border-t border-slate-900 pt-2">
                  <span className="font-semibold text-slate-300">Key Uncertainties:</span>
                  <ul className="list-disc list-inside mt-1 space-y-0.5">
                    {sc.keyUncertainties.map((u, ui) => (
                      <li key={ui}>{u}</li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {analysis.alternativePaths && analysis.alternativePaths.length > 0 && (
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl">
          <div className="flex items-center space-x-2 border-b border-slate-800 pb-3 mb-4">
            <Share2 className="w-5 h-5 text-emerald-400" />
            <h3 className="text-base font-bold text-white">4. Alternative Paths & Compromise Options</h3>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {analysis.alternativePaths.map((alt, idx) => (
              <div key={idx} className="bg-slate-950 border border-slate-800 p-4 rounded-2xl">
                <h4 className="text-sm font-bold text-amber-300 mb-1">{alt.optionTitle}</h4>
                <p className="text-xs text-slate-300 mb-2">{alt.description}</p>
                <p className="text-[11px] text-slate-400 bg-slate-900 p-2.5 rounded-xl border border-slate-800">
                  <span className="text-slate-200 font-semibold">Trade-off vs Primary Option:</span> {alt.tradeoffComparison}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl">
        <div className="flex items-center space-x-2 border-b border-slate-800 pb-3 mb-4">
          <Scale className="w-5 h-5 text-amber-400" />
          <h3 className="text-base font-bold text-white">5. Perspective Balance Matrix</h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-emerald-950/20 border border-emerald-500/20 rounded-2xl p-4">
            <h4 className="text-xs font-bold text-emerald-400 uppercase tracking-wider mb-2 flex items-center gap-1">
              <CheckCircle className="w-4 h-4" /> Highly Visible Benefits (Primary Drivers)
            </h4>
            <ul className="space-y-1.5 text-xs text-slate-300">
              {analysis.perspectiveBalance.prosVisible.map((pro, i) => (
                <li key={i} className="flex items-start space-x-2">
                  <span className="text-emerald-400 font-bold">•</span>
                  <span>{pro}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="bg-rose-950/20 border border-rose-500/20 rounded-2xl p-4">
            <h4 className="text-xs font-bold text-rose-400 uppercase tracking-wider mb-2 flex items-center gap-1">
              <ShieldAlert className="w-4 h-4" /> Hidden Trade-Offs (Secondary Costs)
            </h4>
            <ul className="space-y-1.5 text-xs text-slate-300">
              {analysis.perspectiveBalance.hiddenTradeoffs.map((tradeoff, i) => (
                <li key={i} className="flex items-start space-x-2">
                  <span className="text-rose-400 font-bold">•</span>
                  <span>{tradeoff}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center space-x-2">
            <HelpCircle className="w-5 h-5 text-yellow-400" />
            <h3 className="text-base font-bold text-white">6. Critical Probing Questions for Self-Reflection</h3>
          </div>
          <span className="text-xs text-slate-400">Click to check off questions you have pondered</span>
        </div>

        <div className="space-y-3">
          {analysis.probingQuestions.map((q, idx) => {
            const isChecked = !!completedQuestions[idx];
            return (
              <button
                key={idx}
                onClick={() => toggleQuestion(idx)}
                className={`w-full text-left p-4 rounded-2xl border transition flex items-start space-x-3 ${
                  isChecked
                    ? 'bg-amber-500/10 border-amber-500/40 text-amber-200'
                    : 'bg-slate-950 border-slate-800 text-slate-200 hover:border-slate-700'
                }`}
              >
                {isChecked ? (
                  <CheckSquare className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
                ) : (
                  <Square className="w-5 h-5 text-slate-500 shrink-0 mt-0.5" />
                )}
                <div className="min-w-0">
                  <p className="text-sm font-medium leading-relaxed">{q}</p>
                  <p className="text-[11px] text-slate-400 mt-1">
                    {isChecked ? '✓ Marked as considered' : 'Click when you have answered this for yourself'}
                  </p>
                </div>
              </button>
            );
          })}
        </div>
      </div>
    </div>
  );
};
